import React from 'react';
import {
  Container,
  Typography,
  Box,
  Divider,
  List,
  ListItem,
  ListItemText,
} from '@mui/material';

const Termscondition = () => {
  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Typography variant="h3" component="h1" gutterBottom align="center">
        Terms & Conditions
      </Typography>
      <Typography variant="subtitle1" color="text.secondary" align="center" gutterBottom>
        Posted as of 29 January, 2022 | Last updated as of 29 January, 2022
      </Typography>
      <Divider sx={{ my: 3 }} />

      <Box sx={{ mb: 4 }}>
        <Typography variant="h5" gutterBottom>
          Introduction
        </Typography>
        <Typography variant="body1" paragraph>
          This legal agreement is an electronic record in terms of the Indian Information Technology
          Act, 2000 and rules thereunder as applicable and the amended provisions about electronic
          records in various statutes as amended by the Indian Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not require any physical or
          digital signatures.
        </Typography>
        <Typography variant="body1" paragraph>
          This legal document is published in accordance with the provisions of Rule 3 (1) of the
          Indian Information Technology (Intermediaries guidelines) Rules, 2011 and Rule 4 of the
          Information Technology (Reasonable security practices and procedures and sensitive personal
          data or information) Rules, 2011 of Information Technology Act, 2000 amended through
          Information Technology Amendment Act, 2008 that require publishing the Terms of Use and
          practices for access and usage of any functional Application.
        </Typography>
        <Typography variant="body1" paragraph>
          This Application is created and operated by M/s Cotyledon Technology Private Limited
          (hereinafter referred to as “We”, “Our”, and “Us”) having its registered address at “11/198
          Mambakkam Main Road, Medavakkam, Chennai- 600100, Tamil Nadu India” and operating under the
          brand name “Pick Your Slot (PYS)” (“Brand name”). We intend to ensure your steady commitment
          to the usage of this Application and the services provided by us through our Application
          “Pick Your Slot (PYS)” (“Application”).
        </Typography>
      </Box>

      <Box sx={{ mb: 4 }}>
        <Typography variant="h5" gutterBottom>
          Definitions
        </Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="i."
              secondary='“We”, “Firm”, “Our”, and “Us” shall mean and refer to the Application.'
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="ii."
              secondary='“You”, “Your”, “Yourself”, “User” shall mean and refer to natural and legal individuals who shall be users of this Application provided by us and who is competent to enter into binding contracts, as per Indian laws.'
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="iii."
              secondary='“Third Parties” refer to any Application or individual apart from the Users and the creator of this Application.'
            />
          </ListItem>
        </List>
      </Box>

      <Box sx={{ mb: 4 }}>
        <Typography variant="h5" gutterBottom>
          General Terms
        </Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="i."
              secondary="The headings of each section in these Terms of Use are only for the purpose of organizing the various provisions under these Terms of Use in an orderly manner and shall be used by you to interpret the provisions contained herein in a manner as may apply to you. Further, it is specifically agreed by you that the headings shall have legal or contractual value on your usage of the Application."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="ii."
              secondary="The use of this Application is solely governed by these Terms of Use, Privacy Policy that may be uploaded on the Application and any modifications or amendments made thereto by us from time to time, at our sole discretion. If you as a user continue to access and use this Application, you are agreeing to comply with and be bound by the following Terms of Use and Privacy Policy."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="iii."
              secondary="You expressly agree and acknowledge that these Terms of Use and Privacy Policy are co-terminus in nature and that expiry/termination of either one will lead to the termination of the other."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="iv."
              secondary="You unequivocally agree that these Terms of Use and the Privacy Policy constitute a legally binding agreement between us, and that you shall be subject to the rules, guidelines, policies, terms, and conditions applicable to your use of the Application, and that the same shall be deemed to be incorporated into these Terms of Use and shall be treated as part and parcel of the same. You acknowledge and agree that no signature or express act is required to make these Terms of Use and the Privacy Policy binding on you and that your act of visiting any part of the Application constitutes your full and final acceptance of these Terms of Use and the Privacy Policy."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="v."
              secondary="We reserve the sole and exclusive right to amend or modify these Terms of Use without any prior permission or intimation to you, and you expressly agree that any such amendments or modifications shall come into effect immediately. If you do not adhere to the changes, You must stop using the Application at once. Your continued use of the Application will signify your acceptance of the changed terms."
            />
          </ListItem>
        </List>
      </Box>

      <Box sx={{ mb: 4 }}>
        <Typography variant="h5" gutterBottom>
          Registration
        </Typography>
        <Typography variant="body1" paragraph>
          Registration on the Application is mandatory for Users of the Applications if the Users want
          to purchase from the Application. The Users shall have to provide the following information
          at the time of registration:
        </Typography>
        <List>
          <ListItem>
            <ListItemText primary="i. Name" />
          </ListItem>
          <ListItem>
            <ListItemText primary="ii. Phone Number" />
          </ListItem>
          <ListItem>
            <ListItemText primary="iii. Email ID" />
          </ListItem>
          <ListItem>
            <ListItemText primary="iv. Date of Birth" />
          </ListItem>
          <ListItem>
            <ListItemText primary="v. City" />
          </ListItem>
        </List>
        <Typography variant="body1" paragraph>
          The Users cannot link their social media accounts on the Application.
        </Typography>
      </Box>

      <Box sx={{ mb: 4 }}>
        <Typography variant="h5" gutterBottom>
          Application Overview
        </Typography>
        <Typography variant="body1" paragraph>
          The Application is a services management platform. The Application is committed to bring
          multiple service providers to one platform acting as an aggregator and thereby providing
          multiple options to users for availing their go-to service. The Application provides
          all-in-one complete solution for any of the online available services the user wants to avail
          with instant booking on time.
        </Typography>
        <Typography variant="body1" paragraph>
          The role of the Application is to create a variety of domains for every type of service a
          user avails in his daily life, such as education, architectural and urban design, digital
          marketing and activism, engineering, groceries, shopping, payments entertainment, virtual
          communities, fine arts, healthcare and clinical therapies, heritage and archaeology,
          occupational safety, social science and psychology, etc. The Application undertakes the
          easiest ways to manage bookings for the services and pay per session. The Application
          provides efficient and fast booking, services sections, personalised search, and the services
          management sections.
        </Typography>
        <Typography variant="body1" paragraph>
          The functionalities of the Application operate as follows:
        </Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="1."
              secondary="User has to register on the Application with required personal information to get the login credentials through SMS."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="2."
              secondary="After successful registration, user can book / cancel / Modify the bookings."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="3."
              secondary="User can pay via third party Razor pay application and confirm the bookings for any of the availed services."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="4."
              secondary="Once the user books the slot, they will receive OTP from Application through as SMS."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="5."
              secondary="The User has to reach the specified Vendor and needs to confirm the OTP with Vendor to avail the services."
            />
          </ListItem>
        </List>
      </Box>

      <Box sx={{ mb: 4 }}>
        <Typography variant="h5" gutterBottom>
          Payment Gateway
        </Typography>
        <Typography variant="body1" paragraph>
          For making all payments for services on the Application, you shall be required to make
          payment for which you will be redirected to a third-party payment gateway, that we may have
          an agreement with. The payment gateway may additionally seek information from you to process
          the payment for your purchase and additionally may charge you the payment gateway charges
          that may be applicable. The payment gateway consists of Debit Card/Credit Card/Net
          Banking/UPI and other wallet options. You shall be governed under the concerned payment
          gateway’s Terms and Conditions and other Policies for the purpose of all payment-related
          aspects.
        </Typography>
      </Box>

      {/* Add more sections as needed, following the same structure */}
      <Box sx={{ mb: 4 }}>
        <Typography variant="h5" gutterBottom>
          Contact Us
        </Typography>
        <Typography variant="body1" paragraph>
          If you have any questions about these Terms of Use, the practices of the Application, or
          your experience, you can contact us by emailing at{' '}
          <a href="mailto:info@pickyourslot.com">info@pickyourslot.com</a>.
        </Typography>
      </Box>
    </Container>
  );
};

export default Termscondition;