"use client";
import React from 'react';
import { 
  Container, 
  Typography, 
  Paper, 
  Box, 
  Divider,
  Link,
  List,
  ListItem,
  ListItemText,
  ListItemIcon
} from '@mui/material';
import CircleIcon from '@mui/icons-material/Circle';
import NavBar from '@/component/Home/NavBar';
import Footer from '@/component/Home/Footer';
import BgImg from "@/Assets/video-bg.png";

// Helper component for consistent section structure
const Section = ({ title, children }) => (
  <Box sx={{ mb: 5 }}>
    <Typography variant="h5" component="h2" sx={{ fontWeight: 'bold', mb: 1.5 }}>
      {title}
    </Typography>
    <Divider sx={{ mb: 3 }} />
    {children}
  </Box>
);

// Helper component for consistent list styling
const StyledList = ({ type = 'ul', items, markerType = 'disc' }) => {
  const listStyles = {
    pl: 3,
    '& .MuiListItem-root': {
      paddingTop: 0.5,
      paddingBottom: 0.5,
    },
    '& .MuiListItemText-root': {
      my: 0.5,
      textAlign: 'justify',
    },
    '& .MuiListItemIcon-root': {
      minWidth: 'auto',
      marginRight: 1.5,
      color: 'text.secondary',
      fontSize: '0.6rem',
      alignSelf: 'flex-start',
      mt: '10px'
    },
  };

  const ListComponent = type === 'ol' ? 'ol' : 'ul';
  const getListItemMarker = (index) => {
    if (type === 'ol') {
      if (markerType === 'decimal') return `${index + 1}.`;
      if (markerType === 'lower-alpha') return `${String.fromCharCode(97 + index)}.`;
      if (markerType === 'lower-roman') {
        const romanMap = { 1: 'i', 2: 'ii', 3: 'iii', 4: 'iv', 5: 'v' };
        return `${romanMap[index + 1] || index + 1}.`;
      }
    }
    return <CircleIcon sx={{ fontSize: 'inherit' }} />;
  };

  return (
    <List component={ListComponent} sx={listStyles} disablePadding>
      {items.map((item, index) => (
        <ListItem key={index} disableGutters>
          <ListItemIcon sx={{ alignSelf: type === 'ol' ? 'baseline' : 'flex-start', mt: type === 'ol' ? '2px' : '8px' }}>
            {type === 'ol' ? (
              <Typography component="span" variant="body1" sx={{ color: 'text.secondary', mr: 1.5 }}>
                {getListItemMarker(index)}
              </Typography>
            ) : (
              <CircleIcon sx={{ fontSize: '0.6rem' }} />
            )}
          </ListItemIcon>
          <ListItemText primary={item} primaryTypographyProps={{ variant: 'body1', sx: { textAlign: 'justify' } }}/>
        </ListItem>
      ))}
    </List>
  );
};

export default function TermsAndConditions() {
  return (
    <>
    <Box
      sx={{
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        backgroundImage: `url(${BgImg.src})`,
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        zIndex: -1,
      }}
    />
    <NavBar />
    <br />
    <br />
    <br />
    <br />
    <br />
    <Container maxWidth="lg" sx={{ mt: { xs: 4, md: 8 }, mb: { xs: 8, md: 16 } }}>
      <Paper elevation={3} sx={{ p: { xs: 3, md: 6 }, backgroundColor: 'rgba(255, 255, 255, 0.95)' }}>
        <Box sx={{ textAlign: 'center', mb: 6 }}>
          <Typography variant="h3" component="h1" sx={{ fontWeight: 'bold', mb: 1 }}>
            TERMS & CONDITIONS
          </Typography>
          <Typography variant="subtitle1" color="text.secondary" sx={{ mb: 2 }}>
            Posted as of 29 January, 2022 | Last updated as of 29 January, 2022
          </Typography>
        </Box>

        <Box sx={{ mb: 5 }}>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            This legal agreement is an electronic record in terms of the Indian Information Technology Act, 2000 and rules there under as applicable and the amended provisions about electronic records in various statutes as amended by the Indian Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </Typography>
          
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            This legal document is published in accordance with the provisions of Rule 3 (1) of the Indian Information Technology (Intermediaries guidelines) Rules, 2011 and Rule 4 of the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 of Information Technology Act, 2000 amended through Information Technology Amendment Act, 2008 that require publishing the Terms of Use and practices for access and usage of any functional Application.
          </Typography>
          
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            This Application is created and operated by M/s Cotyledon Technology Private Limited (hereinafter referred to as "We", "Our", and "Us") having its registered address at "11/198 Mambakkam Main Road, Medavakkam, Chennai- 600100, Tamil Nadu India" and operating under the brand name "Pick Your Slot (PYS)" ("Brand name"). We intend to ensure your steady commitment to the usage of this Application and the services provided by us through our Application "Pick Your Slot (PYS)" ("Application").
          </Typography>
        </Box>

        <Section title="DEFINITIONS">
          <StyledList
            items={[
              <>For the purpose of these Terms of Use ("Terms of Use"), wherever the context so requires, <Typography component="span" sx={{ fontWeight: 'bold' }}>"We"</Typography>, <Typography component="span" sx={{ fontWeight: 'bold' }}>"Firm"</Typography>, <Typography component="span" sx={{ fontWeight: 'bold' }}>"Our"</Typography>, and <Typography component="span" sx={{ fontWeight: 'bold' }}>"Us"</Typography> shall mean and refer to the Application.</>,
              <> <Typography component="span" sx={{ fontWeight: 'bold' }}>"You"</Typography>, <Typography component="span" sx={{ fontWeight: 'bold' }}>"Your"</Typography>, <Typography component="span" sx={{ fontWeight: 'bold' }}>"Yourself"</Typography>, <Typography component="span" sx={{ fontWeight: 'bold' }}>"User"</Typography> shall mean and refer to natural and legal individuals who shall be users of this Application provided by us and who is competent to enter into binding contracts, as per Indian laws.</>,
              <> <Typography component="span" sx={{ fontWeight: 'bold' }}>"Third Parties"</Typography> refer to any Application or individual apart from the Users and the creator of this Application.</>
            ]}
            markerType="lower-roman"
            type="ol"
          />
        </Section>

        <Section title="GENERAL TERMS">
          <StyledList
            type="ol"
            markerType="lower-roman"
            items={[
              "The headings of each section in these Terms of Use are only for the purpose of organizing the various provisions under these Terms of Use in an orderly manner and shall be used by you to interpret the provisions contained herein in a manner as may apply to you. Further, it is specifically agreed by you that the headings shall have legal or contractual value on your usage of the Application.",
              "The use of this Application is solely governed by these Terms of Use, Privacy Policy that may be uploaded on the Application and any modifications or amendments made thereto by us from time to time, at our sole discretion. If you as a user continue to access and use this Application, you are agreeing to comply with and be bound by the following Terms of Use and Privacy Policy.",
              "You expressly agree and acknowledge that these Terms of Use and Privacy Policy are co-terminus in nature and that expiry/termination of either one will lead to the termination of the other.",
              "You unequivocally agree that these Terms of Use and the Privacy Policy constitute a legally binding agreement between us, and that you shall be subject to the rules, guidelines, policies, terms, and conditions applicable to your use of the Application, and that the same shall be deemed to be incorporated into these Terms of Use and shall be treated as part and parcel of the same. You acknowledge and agree that no signature or express act is required to make these Terms of Use and the Privacy Policy binding on you and that your act of visiting any part of the Application constitutes your full and final acceptance of these Terms of Use and the Privacy Policy.",
              "We reserve the sole and exclusive right to amend or modify these Terms of Use without any prior permission or intimation to you, and you expressly agree that any such amendments or modifications shall come into effect immediately. If you do not adhere to the changes, You must stop using the Application at once. Your continued use of the Application will signify your acceptance of the changed terms."
            ]}
          />
        </Section>

        <Section title="REGISTRATION">
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            Registration on the Application is mandatory for Users of the Applications if the Users want to purchase from the Application. The Users shall have to provide the following information at the time of registration:
          </Typography>
          <StyledList
            items={[
              "Name",
              "Phone Number",
              "Email ID",
              "Date of Birth",
              "City"
            ]}
            markerType="lower-roman"
            type="ol"
          />
          <Typography variant="body1" paragraph sx={{ mt: 2, lineHeight: 1.7, textAlign: 'justify' }}>
            The Users cannot link their social media accounts on the Application.
          </Typography>
        </Section>

        <Section title="APPLICATION OVERVIEW">
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            The Application is a services management platform. The Application is committed to bring multiple service providers to one platform acting as an aggregator and thereby providing multiple options to users for availing their go-to service. The Application provides all-in-one complete solution for any of the online available services the user wants to avail with instant booking on time.
          </Typography>
          
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            The role of the Application is to create a variety of domains for every type of service a user avails in his daily life, such as education, architectural and urban design, digital marketing and activism, engineering, groceries, shopping, payments entertainment, virtual communities, fine arts, healthcare and clinical therapies, heritage and archaeology, occupational safety, social science and psychology, etc. The Application undertakes the easiest ways to manage bookings for the services and pay per session. The Application provides efficient and fast booking, services sections, personalised search, and the services management sections.
          </Typography>
          
          <Typography variant="body1" paragraph sx={{ mt: 2, lineHeight: 1.7, fontWeight: 'medium', textAlign: 'justify' }}>
            The functionalities of the Application operate as follows:
          </Typography>
          
          <StyledList
            type="ol"
            markerType="decimal"
            items={[
              "User has to register on the Application with required personal information to get the login credentials through SMS.",
              "After successful registration, user can book / cancel / Modify the bookings.",
              "User can pay via third party Razor pay application and confirm the bookings for any of the availed services.",
              "Once the user books the slot, they will receive OTP from Application through as SMS.",
              "The User has to reach the specified Vendor and needs to confirm the OTP with Vendor to avail the services."
            ]}
          />
        </Section>

        <Section title="PAYMENT GATEWAY">
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            For making all payments for services on the Application, you shall be required to make payment for which you will be redirected to a third-party payment gateway, that we may have an agreement with. The payment gateway may additionally seek information from you to process the payment for your purchase and additionally may charge you the payment gateway charges that may be applicable. The payment gateway consists of Debit Card/Credit Card/Net Banking/UPI and other wallet options. You shall be governed under the concerned payment gateway's Terms and Conditions and other Policies for the purpose of all payment-related aspects.
          </Typography>
        </Section>

        <Section title="ELIGIBILITY">
          <StyledList
            type="ol"
            markerType="lower-alpha"
            items={[
              "You represent and warrant that you are competent and eligible to enter into legally binding agreements and of age and that you have the requisite authority to bind themselves to these Terms of Use following the Law. However, if you are a minor using this Application, you may do so with the consent of your legal guardian. All Acts of minor shall be deemed to be considered as the acts undertaken under the supervision of their legal guardian.",
              "You further represent that you will comply with these Terms of Use and all applicable local, state, national and international laws, rules and regulations.",
              "You shall not use the Application if you are not competent to contract or are disqualified from doing so by any other applicable law, rule or regulation currently in force."
            ]}
          />
        </Section>

        <Section title="CONTENT">
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            All text, graphics, User interfaces, visual interfaces, photographs, trademarks, logos, brand names, descriptions, sounds, music and artwork (collectively, 'Content'), is generated/provided or based on information provided by the users or third parties and We have no control and make no guarantees regarding the quality, the accuracy, integrity or genuineness of such content or such other information provided on the Application.
          </Typography>
          
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            All the Content displayed on the Application is subject to copyright and shall not be reused by You (or a third party) without the prior written consent from Us and the copyright owner.
          </Typography>
          
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            You are solely responsible for the integrity, authenticity, quality and genuineness of the content provided on the Application and whilst feedback and comments by You can be made via the Application, we bear no liability whatsoever for any feedback or comments made by the other Users or made in respect of any of the content on the Application. Further, the Application reserves its right to suspend the account of any User for an indefinite period to be decided at the discretion of the Application or to terminate the account of any User who is found to have created or shared or submitted any content or part thereof that is found to be untrue/inaccurate/misleading or offensive/vulgar. You shall be solely responsible for making good any financial or legal losses incurred through the creation/sharing/submission of Content or part thereof that is deemed to be untrue/inaccurate/misleading.
          </Typography>
          
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            You have a personal, non-exclusive, non-transferable, revocable, limited privilege to access the content on the Application. You shall not copy, adapt, and modify any content without written permission from Us.
          </Typography>
        </Section>

        <Section title="INDEMNITY">
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            You agree to indemnify, defend and hold harmless the Us, and our respective directors, officers, employees and agents (collectively, "Parties"), from and against any losses, liabilities, claims, damages, demands, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by Us that arise out of, result from, or maybe payable by, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed according to these Terms of Use. Further, You agrees to hold the Us harmless against any claims made by any third party due to, or arising out of, or in connection with:
          </Typography>
          
          <StyledList
            type="ol"
            markerType="lower-alpha"
            items={[
              "Your use of the Application,",
              "Your violation of these Terms of Use;",
              "Your violation of any rights of another;",
              "Your alleged improper conduct according to these Terms of use;",
              "Your conduct in connection with the Application;"
            ]}
          />
          
          <Typography variant="body1" paragraph sx={{ mt: 2, lineHeight: 1.7, textAlign: 'justify' }}>
            You agree to fully cooperate in indemnifying Us at your expense. You also agree not to settle with any party without consent from Us.
          </Typography>
          
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            In no event shall we be liable to compensate You or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable, and whether or not You had been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence or other tortuous action, or any other claim arising out of or in connection with the Your use of or access to the Application and/or the Services or materials contained therein.
          </Typography>
        </Section>
        
        <Section title="LIMITATION OF LIABILITY">
          <StyledList
            type="ol"
            markerType="lower-alpha"
            items={[
              <>
                We are not responsible for any consequences arising out of the following events:
                <StyledList
                  type="ol"
                  markerType="lower-roman"
                  items={[
                    "If the Application is inoperative/non-responsive due to any connectivity errors associated with the internet connection such as but not limited to slow connectivity, no connectivity, server failure;",
                    "If you have fed incorrect information or data or for any deletion of data;",
                    "If there is an undue delay or inability to communicate through email;",
                    "If there is any deficiency or defect in the Services managed by Us;",
                    "If there is a failure in the functioning of any other service provided by Us."
                  ]}
                />
              </>,
              "The Application accepts no liability for any errors or omissions, on behalf of itself, or for any damage caused to You, Your belongings, or any third party, resulting from the use or misuse of the Application or any service availed of by Us through the Application. The service and any Content or material displayed on the service is provided without any guarantees, conditions or warranties as to its accuracy, suitability, completeness or reliability. We will not be liable to you for the unavailability or failure of the Application.",
              "You are to comply with all laws applicable to you or your activities, and with all Policies, which are hereby incorporated into this Terms of Use by reference.",
              "The Application expressly excludes any liability for any loss or damage that was not reasonably foreseeable by the Application and which is incurred by you in connection with the Application, including loss of profits; and any loss or damage incurred by you as a result of your breach of these Terms of Use.",
              "To the fullest extent permitted by law, We shall not be liable to You or any other party for any loss or damage, regardless of the form of action or basis of any claim. You acknowledge and agree that your sole and exclusive remedy for any dispute with us is to terminate your use of the Application."
            ]}
          />
        </Section>
        
        <Section title="TERM">
          <StyledList
            type="ol"
            markerType="lower-alpha"
            items={[
              "These Terms of Use shall continue to form a valid and binding contract between us and shall continue to be in full force and effect until you continue to access and use the Applications.",
              "You may terminate your use of the Application at any time.",
              "We may terminate these Terms of Use and close your account at any time without notice and/or suspend or terminate Your access to the Application at any time and for any reason, if any discrepancy or legal issue arises.",
              "Such suspension or termination shall not limit our right to take any other action against you that we consider appropriate.",
              "It is also hereby declared that we may discontinue the Services and Applications without any prior notice."
            ]}
          />
        </Section>

        <Section title="TERMINATION">
          <StyledList
            type="ol"
            markerType="lower-alpha"
            items={[
              "We reserve the right, in its sole discretion, to unilaterally terminate Your access to the Application, or any portion thereof, at any time, without notice or cause.",
              "We also reserve the universal right to deny access to You, to any/all of are on its Application without any prior notice/explanation to protect the interests of the Application and/or other Users to the Application.",
              "We reserve the right to limit, deny or create different access to the Application and its features concerning different Users, or to change any of the features or introduce new features without prior notice.",
              "You shall continue to be bound by these Terms of use, and it is expressly agreed to by You that You shall not have the right to terminate these Terms of Use till the expiry of the same."
            ]}
          />
        </Section>
        
        <Section title="COMMUNICATION">
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            By using this Application and providing Your identity and contact information to Us through the Application, You agree and consent to receive calls, e-mails or SMS from Us and/or any of its representatives at any time.
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            You can report to <Link href="mailto:info@pickyourslot.com">info@pickyourslot.com</Link> if you find any discrepancy with regard to Application or content-related information and we will take necessary action after an investigation. The response with resolution (if any issues found) shall be dependent on the time is taken for investigation.
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            You expressly agree that notwithstanding anything contained herein above, it may be contacted by Us relating to any services availed by You on the Application or anything pursuant thereto and You agree to indemnify Us from any harassment claims. It is expressly agreed to by Us that any information shared by Us shall be governed by the Privacy Policy.
          </Typography>
        </Section>
        
        <Section title="USER OBLIGATIONS AND FORMAL UNDERTAKINGS AS TO CONDUCT">
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7, textAlign: 'justify' }}>
            You agree and acknowledges that you are a restricted user of this Application and you:
          </Typography>
          <StyledList
            type="ol"
            markerType="lower-alpha"
            items={[
              "Agree to provide genuine credentials during the process whenever required on the Application. You shall not use a fictitious identity to register. We are not liable if you have provided incorrect information.",
              "Agree to ensure the Name, Email address, Address, Mobile number and any such other information that may be provided during account registration is valid at all times and shall keep your information accurate and up-to-date.",
              "Agrees that the User shall be entirely responsible for all activities that the user shall undertake post making the booking with the service provider/vendor and the user shall undertake sole responsibility towards any activities including but not limited to vehicle accidents, smuggling, trafficking, any illegal or prohibited activities. Further, the user shall waive all its rights to undertake any action against us towards any breach of personally identifiable information.",
              "You agree that You are solely responsible for maintaining the confidentiality of your account password. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to close your account at any time for any or no reason.",
              "The User represents and warrants that the User shall undertake to exclude any liability and hold the Firm harmless for any legal action that may arise for the Firm due to the user's activities which may involve any type of illegal activities in which the user undertakes to use the services of the vendor under the influence of drugs, alcohol, or for smuggling, trafficking etc which may or may not involve prohibited substances and commodities or if there arises any legal action against the Firm under the provisions of the Indian penal code.",
              "The User further represents and warrants that the negotiations and the discussions between the user and the vendor shall be at their sole discretion and the Firm in no manner shall be made a party to such discussions that may involve the vendor's services to the user. Such discussions and negotiations may include but not limited to the payment and payment terms.",
              "The User represents and warrants that We are not responsible for the operation of vendors, nor the content uploaded by them.",
              "The User represents and warrants that the Firm shall have a limited liability to provide the user with a basic acknowledgement on the condition of the vehicle that may be provided by the vendor. However, the Vendor shall be solely responsible for all the quality and the condition of the vehicle provided by the Vendor to the user and the user shall in no manner bring out any suit or thereby any legal action against the Firm.",
              "User represents and warrants that the Firm may offer other additional accidental insurance packages from any third parties, which will benefit the user. However, the Firm does not guarantee the user the same at any time.",
              "Authorize the Application to use, store or otherwise process certain personal information and all published Content, responses, locations, User comments, reviews and ratings for personalization of Services, marketing and promotional purposes and for optimisation of User-related options and Services.",
              "Understand and agree that, to the fullest extent permissible by law, the Application or any of their affiliates or their respective officers, directors, employees, agents, licensors, representatives, operational service providers, advertisers or suppliers shall not be liable for any loss or damage, of any kind, direct or indirect, in connection with or arising from the use of the Application or this terms of use, including, but not limited to, compensatory, consequential, incidental, indirect, special or punitive damages.",
              "Are bound not to cut, copy, modify, recreate, reverse engineer, distribute, disseminate, post, publish or create derivative works from, transfer, or sell any information or obtained from the Application. Any such use/limited use of the Application will only be allowed with the prior express written permission.",
              "Agree that promotions and giveaways are governed by a different set of rules.",
              "Agree that We are only responsible for the advance payments made to Us and not the offline payments made to the Vendors.",
              "Agree not to access (or attempt to access) the Application and/or the materials or Services by any means other than through the interface provided by the Application. The use of deep-link, robot, spider or other automatic devices, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Application or its content, or in any way reproduce or circumvent the navigational structure or presentation of the Application, materials or any content, or to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Application will lead to suspension or termination of your access to the Application. We disclaim any liabilities arising concerning such offensive content on the Application.",
              "Expressly agree and acknowledge that the Content generated by the Users and displayed on the Application is not owned by Us and that We are in no way responsible for the content of the same. You may, however, report any offensive or objectionable content, which We may then remove from the Application, at our sole discretion."
            ]}
          />
           <Typography variant="body1" paragraph sx={{ mt: 2, lineHeight: 1.7, fontWeight: 'medium' }}>
             You further undertake not to:
           </Typography>
          <StyledList
             type="ol"
             markerType="lower-alpha" // Corresponds to a, b, c...
             items={[
               "Engage in any activity that interferes with or disrupts access to the Application or the services provided therein (or the servers and networks which are connected to the Application);",
               "Impersonate any person or entity, or falsely state or otherwise misrepresent his/her affiliation with a person or entity;",
               "Probe, scan or test the vulnerability of the Application or any network connected to the Application, nor breach the security or authentication measures on the Application or any network connected to the Application. The User may not reverse look-up, trace or seek to trace any information relating to any other User of, or visitor to, the Application, or any other viewer of the Application, including any User account maintained on the Application not operated/managed by the User, or exploit the Application or information made available or offered by or through the Application, in any manner;",
               "Disrupt or interfere with the security of, or otherwise cause harm to, the Application, systems resources, accounts, passwords, servers, or networks connected to or accessible through the Application or any affiliated or linked Applications.",
               "Use the Application or any material or content therein for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Application or any other third party (s);",
               "Violate any code of conduct or guideline which may apply for or to any particular service offered on the Application;",
               "Violate any applicable laws, rules or regulations currently in force within or outside India;",
               "Violate any portion of these Terms of Use or the Privacy Policy, including but not limited to any applicable additional terms of the Application contained herein or elsewhere, whether made by amendment, modification, or otherwise;",
               "Commit any act that causes Us to lose (in whole or in part) the Services of its Internet Establishment (\"ISP\") or in any manner disrupts the Services of any other supplier/service provider of the Application;",
               "You hereby expressly authorize Us to disclose any and all information relating to You in our possession to law enforcement or other government officials, as We may in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those involve personal injury and theft/infringement of intellectual property. You further understand that the Application might be directed to disclose any information (including the identity of persons providing information or materials on the Application) as necessary to satisfy any judicial Order, law, regulation or valid governmental request.",
               "By indicating Your acceptance to use any services offered on the Application, You are obligated to complete such transactions after making payment. You shall be prohibited from indicating their acceptance to avail services where the transactions have remained incomplete.",
               "You agree to use the services provided by Us, our affiliates, consultants and contracted companies, for lawful purposes only.",
               "You agree to provide authentic and true information. We reserve the right to confirm and validate the information and other details provided by You at any point in time. If upon confirmation such details are found to be false, not to be true (wholly or partly), We shall in our sole discretion reject the registration and debar You from using the Application without prior intimation whatsoever.",
                <>
                 You agree not to post any material on the Application that is defamatory, offensive, obscene, indecent, abusive, or needlessly distressful or advertising any goods or services. More specifically, You agree not to host, display, upload, update, publish, modify, transmit, or in any manner share any information that:
                 <StyledList
                   type="ol"
                   markerType="lower-roman" // Nested list i, ii, iii...
                   items={[
                     "belongs to another person and to which you have no right to;",
                     "is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;",
                     "is in any way harmful to minors;",
                     "infringes any patent, trademark, copyright or other proprietary rights;",
                     "violates any law for the time being in force;",
                     "deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing;",
                     "Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of others;",
                     "Impersonate any person or entity, or falsely state or otherwise misrepresent Your affiliation with a person or entity;",
                     "Publish, post, disseminate, any grossly harmful information, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to \"indecent representation of women\" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;",
                     "Threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation."
                   ]}
                 />
               </>
             ]}
           />
        </Section>

        {/* Suspension of User Access Section */}
        <Section title="SUSPENSION OF USER ACCESS AND ACTIVITY">
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7 }}>
            Notwithstanding other legal remedies that may be available, we may in our sole discretion, limit your access and/or activity by immediately removing your access credentials either temporarily or indefinitely, or suspend/terminate your association with the Application, and/or refuse to the usage of the Application, without being required to provide you with notice or cause:
          </Typography>
           <StyledList
             type="ol"
             markerType="lower-alpha" // Corresponds to a, b, c
             items={[
               "If you are in breach of any of these Terms of Use or the Privacy Policy;",
               "If you have provided wrong, inaccurate, incomplete or incorrect information;",
               "If your actions may cause any harm, damage or loss to the other Users or Us, at our sole discretion."
             ]}
           />
        </Section>

        {/* Intellectual Property Rights Section */}
        <Section title="INTELLECTUAL PROPERTY RIGHTS">
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7 }}>
            Unless expressly agreed to in writing, nothing contained herein shall give you a right to use any of the trade names, trademarks, service marks, logos, domain names, information, questions, answers, solutions, reports and other distinctive brand features, save according to the provisions of these Terms of Use that shall be available on the Application. All logos, trademarks, brand names, service marks, domain names, including material, designs, and graphics created by and developed by either the Application or such other third party and other distinctive brand features of the Application are the property of the Application or the respective copyright or trademark owner. Furthermore, concerning the Application, we shall be the exclusive owner of all the designs, graphics and the like, related to the Application.
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7 }}>
            You shall not use any of the intellectual property displayed on the Application in any manner that is likely to cause confusion among existing or prospective users of the Application, or that in any manner disparages or discredits the Application, to be determined in the sole discretion.
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7 }}>
            You are aware all intellectual property, including but not limited to copyrights, relating to said services resides with the owners, and that at no point does any such intellectual property stand transferred from the aforementioned creators. You are aware that we merely provide the Application through which You can communicate with other users and the Application does not own any of the intellectual property relating to the independent content displayed on the Application, apart from created graphics and specified content.
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.7 }}>
            You are further aware that any reproduction or infringement of the intellectual property of the aforementioned owners by You will result in legal action being initiated against You by the respective owners of the intellectual property so reproduced/infringed upon. It is agreed to by You that the contents of this section shall survive even after the termination or expiry of these Terms of Use and/or Privacy Policy.
          </Typography>
        </Section>
        
         {/* Disclaimer of Warranties Section */}
        <Section title="DISCLAIMER OF WARRANTIES AND LIABILITIES">
           <StyledList
             type="ol"
             markerType="lower-alpha" // Corresponds to a, b, c, d
             items={[
                "You further agree and undertake that you are accessing the Application at your sole risk and are that you are using the best and prudent judgment before availing of any features on the Application or accessing/using any information displayed thereon.",
                "You agree that any kind of information, resources, activities, recommendations obtained/availed from the Application, written or oral, will not create any warranty and we disclaim all liabilities resulting from these.",
                "We do not guarantee that the features and content contained in the Application will be uninterrupted or error-free, or that the Application or its server will be free of viruses or other harmful components, and You hereby expressly accepts any associated risks involved with your use of the Application.",
                "It is further agreed to by You that the contents of this section shall survive even after the termination or expiry of the Terms of Use and/or Privacy Policy."
             ]}
           />
        </Section>
        
        {/* Force Majeure Section */}
        <Section title="FORCE MAJEURE">
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.7 }}>
                We will not be liable for damages for any delay or failure to perform our obligations hereunder if such delay or failure is due to cause beyond our control or without its fault or negligence, due to Force Majeure events including but not limited to acts of war, acts of God, earthquake, riot, fire, festive activities sabotage, labour shortage or dispute, internet interruption, technical failure, breakage of sea cable, hacking, piracy, cheating, illegal or unauthorized.
            </Typography>
        </Section>
        
        {/* Dispute Resolution Section */}
        <Section title="DISPUTE RESOLUTION AND JURISDICTION">
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.7 }}>
                In the event of any dispute arising out of or in connection with this agreement, including any dispute relating to the validity of this agreement, the parties shall, at first instance, attempt to resolve the dispute by mediation administered by the Centre for Online Resolution of Disputes (“CORD”) (<Link href="http://www.resolveoncord.com" target="_blank" rel="noopener noreferrer">www.resolveoncord.com</Link>) and conducted in accordance with the CORD Rules of Mediation, by a sole mediator to be appointed by CORD.
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.7 }}>
                In the event the parties are unable to resolve any such dispute through mediation within 45 days of the initiation of the dispute, subject to a contrary agreement between the parties, the dispute shall be finally resolved by arbitration administered by CORD and conducted in accordance with the Rules of Arbitration of CORD, by a sole arbitrator to be appointed by CORD. The language of arbitration shall be English. The seat of arbitration shall be Chennai, Tamil Nadu, India.
            </Typography>
             <Typography variant="body1" paragraph sx={{ lineHeight: 1.7 }}>
                You expressly agree that the Terms of Use, Privacy Policy and any other agreements entered into between the Parties are governed by the laws, rules, and regulations of India.
            </Typography>
        </Section>
        
        {/* Miscellaneous Provisions Section */}
        <Section title="MISCELLANEOUS PROVISIONS">
           <StyledList
             type="ol"
             markerType="lower-alpha" // Corresponds to a, b, c
             items={[
               <>
                <Typography component="span" sx={{ fontWeight: 'bold' }}>Entire Agreement:</Typography> These Terms of Use, read with the Privacy Policy, form the complete and final contract between us with respect to the subject matter hereof and supersedes all other communications, representations, and agreements (whether oral, written or otherwise) relating thereto.
               </>,
               <>
                <Typography component="span" sx={{ fontWeight: 'bold' }}>Waiver:</Typography> The failure at any time to require performance of any provision of these Terms of Use shall in no manner affect our right at a later time to enforce the same. No waiver by us of any breach of these Terms of Use, whether by conduct or otherwise, in any one or more instances, shall be deemed to be or construed as a further or continuing waiver of any such breach, or a waiver of any other breach of these Terms of Use.
               </>,
               <>
                <Typography component="span" sx={{ fontWeight: 'bold' }}>Severability:</Typography> If any provision/clause of these Terms of Use is held to be invalid, illegal or unenforceable by any court or authority of competent jurisdiction, the validity, legality, and enforceability of the remaining provisions/clauses of these Terms of Use shall in no way be affected or impaired thereby, and each such provision/clause of these Terms of Use shall be valid and enforceable to the fullest extent permitted by law. In such case, these Terms of Use shall be reformed to the minimum extent necessary to correct any invalidity, illegality or unenforceability, while preserving to the maximum extent the original rights, intentions and commercial expectations of the Parties hereto, as expressed herein.
               </>,
               <>
                 <Typography component="span" sx={{ fontWeight: 'bold' }}>Contact Us:</Typography> If you have any questions about these Terms of Use, the practices of the Application, or your experience, you can contact us by emailing at <Link href="mailto:info@pickyourslot.com">info@pickyourslot.com</Link>.
               </>
             ]}
           />
        </Section>


        {/* Enhanced Contact Us Box at the end */}
        <Box sx={{ 
            mt: 6, 
            p: 3, 
            backgroundColor: (theme) => theme.palette.mode === 'light' ? theme.palette.grey[100] : theme.palette.grey[900] , // Subtle background
            borderRadius: 1 // Standard border radius
            }}>
          <Typography variant="h6" component="h2" sx={{ mb: 2, fontWeight: 'bold' }}>CONTACT US</Typography>
          <Typography variant="body1" sx={{ lineHeight: 1.7 }}>
            If you have any questions about these Terms of Use, the practices of the Application, or your experience with our services, please don't hesitate to reach out. You can contact us by emailing at <Link href="mailto:info@pickyourslot.com" sx={{ fontWeight: 'medium' }}>info@pickyourslot.com</Link>.
          </Typography>
        </Box>
      </Paper>
    </Container>
    <Footer />
    </>
  );
}